package model;

public class Book extends BibliographicPtoducts{
    

    public Book (String name, int pageNumber, GregorianCalendar publicationDate, double price) {
        super(name, pageNumber, publicationDate, price);
    }
    // must generate a unique 3 hexadecimal digit identifier (1,2,3,4,5,6,7,8,9,A,B,C,D,E,F) may be generated by placing a 0x before the number
    public String generateBookID() {

    }
}
